---
- name: Copy `include`
  hosts: hosts_o
  become: yes

  tasks:

  - name: Make directiry '/opt/dev-ops/nginx/include'
    file:
        path: /opt/dev-ops/nginx/include
        state: directory


  - name: Copy config 'log_format'
    template:
      src: log_format.conf.j2
      dest: /opt/dev-ops/nginx/include/log_format.conf
    become: yes

  - name: Copy config 'requestid_dmz'
    template:
      src: requestid_dmz.conf.j2
      dest: /opt/dev-ops/nginx/include/requestid_dmz.conf
    become: yes


  - name: Start service nginx
    service: 
      name: nginx 
      state: started