---
- name: Copy `conf`
  hosts: hosts_n
  become: yes

  tasks:

  - name: Stop service nginx
    service: 
      name: nginx 
      state: stopped

  - name: Backup old 'nginx.conf' in '/etc/nginx/'
    shell: |
      sudo mv /etc/nginx/nginx.conf /etc/nginx/nginx_"$(date +"%H-%M-%S_%d-%m-%y")".conf
    ignore_errors: True

  - name: Make directiry '/opt/dev-ops/nginx/'
    file:
        path: /opt/dev-ops/nginx
        state: directory

  - name: Copy nginx.conf to '/opt/dev-ops/nginx/'
    template:
      src: nginx.conf.j2
      dest: /opt/dev-ops/nginx/nginx.conf
    become: yes

  - name: Create a symbolic link from '/etc/nginx/nginx.conf' to '/opt/dev-ops/nginx/nginx.conf'
    file:
      src: /opt/dev-ops/nginx/nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      state: link
