---
- name: Install nginx
  hosts: hosts_o
  become: yes

  tasks:

  - name: Meke directiry 'upstreams'
    file:
        path: /opt/dev-ops/nginx/upstreams
        state: directory

  - name: Copy upstream kube.workers
    template:
      src: kube.workers.conf.j2
      dest: /opt/dev-ops/nginx/upstreams/kube.workers.conf
    become: yes

  - name: Copy upstreams to kube.dashboard
    template:
      src: kube.dashboard.conf.j2
      dest: /opt/dev-ops/nginx/upstreams/kube.dashboard.conf
