---
- name: Install nginx
  hosts: hosts_o
  become: yes

  tasks:

  - name: Stop service nginx
    service: 
      name: nginx 
      state: stopped

  - name: Backup old nginx.conf
    shell: |
      sudo mv /etc/nginx/nginx.conf /etc/nginx/nginx_"$(date +"%H-%M-%S_%d-%m-%y")".conf
    ignore_errors: True

  - name: Copy nginx.conf
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    become: yes