---

# note only sudo password for increase privelege to sudo

ansible_user            : usr1
ansible_password        : usr123123
ansible_become_password : usr123123


# ----### preinstall tasks ###--------------------------------------------------
# copy key from prifile

source_file             : /home/user/.ssh/id_rsa.pub     # path to rsa key /home/<user>/.ssh/id_rsa.pub
dest_file               : "/home/{{ ansible_user }}/.ssh/authorized_keys"

dest_ssh                : /etc/ssh/sshd_config


# /etc/hosts
# if using DNS comment in task/main.yml - import_playbook: hosts.yml

server_main             : ubuntudesktop64     # static hostname

server_main_ip          : 10.1.1.5            # for test using main host to start playbook


# timezone
# check timezone - `$ timedatectl list-timezones | grep Moscow`

time_zone               : Europe/Moscow


# ----### kubernetes tasks ###---------------------------------------------------
# service 
dest_service            : /etc/profile.d/path.sh 
    
# kubernetes user

kube_user               : kubemaster
kube_user_home_path     : "/home/{{ kube_user }}/"
