---
- name: Reboot all servers
  hosts: all
  become: yes

  tasks:

  - name: Reboot servers
    shell: sleep 3 && reboot now # если перезапустить сразу, можно получить ошибку, делаем паузу
    async: 45                     # выполняет асинхронно команду, т.е. выжидает
    poll: 30                      # 0 указывает, что не будет ждать завершения выполнения команды

  - name: Wait till my server will come up online
    wait_for:                    # переменная запускающее условие
      host: "{{ inventory_hostname }}"
      state: started             # ждем состояние хоста
      delay: 35                   # пауза перед ожиданием
      timeout: 40                # всего времени сколько ждать
    delegate_to: 127.0.0.1       # где будет выполняться ожидание, локально