---
- name: Installing Kubernetetes’ Dependencies
  hosts: kuber_hosts
  become: yes

  tasks:

## / remove old configuration and cluster
## /
## / comment section if first deploy
    - name: kubeadm reset & reset all config 
      shell: sudo kubeadm reset -f
      ignore_errors: yes
    - shell: sudo systemctl stop kubelet 
      ignore_errors: yes
    - shell: sudo systemctl stop docker 
      ignore_errors: yes
    - shell: sudo rm -rf /var/lib/cni/ 
      ignore_errors: yes
    - shell: sudo rm -rf /var/lib/kubelet/* 
      ignore_errors: yes
    - shell: sudo rm -rf /etc/cni/ 
      ignore_errors: yes
    - shell: sudo ifconfig flannel.1 down 
      ignore_errors: yes
    - shell: sudo ifconfig docker0 down 
      ignore_errors: yes
    - shell: sudo ip link delete flannel.1
      ignore_errors: yes
    - shell: sudo rm -rf /var/lib/etcd/*
      ignore_errors: yes

    - name: tmp rm /etc/kubernetes/
      shell: sudo rm -rf /etc/kubernetes/*
## / end comment
## / 

    - name: purge
      shell: sudo apt-get purge kubeadm kubectl kubelet kubernetes-cni kube* -y --allow-change-held-packages 
      ignore_errors: yes
    - name: rm -rf .kube
      shell: sudo rm -rf /home/{{ kube_user }}/.kube
      ignore_errors: yes
    - name: remove kubelet kubeadm kubectl
      shell: sudo apt-get remove kubelet kubeadm kubectl -y --allow-change-held-packages
      ignore_errors: yes
    - name: delete old version of docker
      become: yes
      shell: |
        apt-get update && apt-get install -y \
        apt-transport-https ca-certificates curl software-properties-common gnupg2
        sudo apt-get remove docker docker-engine docker.io containerd runc -y
      ignore_errors: yes

    - name: install new Docker
      shell: |
        apt-get dist-upgrade -y
        sudo curl -fsSL get.docker.com | sh

        sudo systemctl daemon-reload
        sudo systemctl restart docker



    - name: Letting iptables see bridged traffic
      shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        EOF
        sudo sysctl --system

        sudo apt-get update && sudo apt-get install -y apt-transport-https curl
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
        deb https://apt.kubernetes.io/ kubernetes-xenial main
        EOF

    - name: Install kubelet & kubeadm
      shell: |
        sudo apt-get update
        sudo apt-get install -y kubelet kubeadm
        sudo apt-mark hold kubelet kubeadm

        
    - name: daemon-reload
      shell: sudo systemctl daemon-reload      


- hosts: kuber_master
  become: yes

  tasks:

    - name: install kubectl
      apt:
        name: kubectl
        state: present
        force: yes


- name: autoremove
  hosts: kuber_hosts
  become: yes

  tasks:
    - shell: sudo apt autoremove -y
