---
- hosts: kuber_master
  become: yes
  gather_facts: false
  
  tasks:

    - name: get join command
      become_user: "{{ kube_user }}"
      shell: sudo kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: kuber_worker
  become: yes

  tasks:

    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      shell: sudo swapoff -a

    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'



- hosts: kuber_worker
  become: yes
  become_user: "{{ kube_user }}"

  tasks:

    - name: remove kubelet.conf
      shell: sudo rm -rf /etc/kubernetes/kubelet.conf

    - name: delete ca.crt
      shell: sudo rm -rf /etc/kubernetes/pki/ca.crt

    - name: join cluster
      become_user: "{{ kube_user }}"
      shell: sudo {{ hostvars['master'].join_command }} --ignore-preflight-errors=yes > /home/{{ kube_user }}/node_joined.txt




# - hosts: kuber_worker
#   become: yes

#   tasks:

#     - name: Reenable SWAP in fstab (1/2)
#       replace:
#         path: /etc/fstab
#         regexp: '^# (.+?\sswap\s+sw\s+.*)$'
#         replace: '\1'

#     - name: Enable SWAP (2/2)
#       shell: |
#         sudo swapon -a
