---
- name: time_hosts
  hosts: preinstall_hosts
  become: yes

  tasks:

    - name: copy old hosts config
      shell: sudo mv -f /etc/hosts /etc/hosts.bk
      ignore_errors: yes


    - name: Add mappings to /etc/hosts
      template:
        src: hosts.j2
        dest: /etc/hosts
