---
- name: time_hosts
  hosts: preinstall_hosts
  become: yes

  tasks:

    - name: update & upgrade system
      shell: sudo apt update && apt upgrade -y

    - name: install snap
      shell: sudo apt install snapd -y

    - name: Timezone
      shell: |
        sudo timedatectl set-timezone {{ time_zone }}

    - name: Install ntpdate
      apt:
        name: ntp
        state: latest

    - name: Add ntp servers
      shell: |
        sudo mv /etc/ntp.conf /etc/ntp.conf.$(date +%F_%R)
        sudo echo 'server 0.ru.pool.ntp.org prefer iburst' > /etc/ntp.conf
        sudo echo 'server 1.ru.pool.ntp.org prefer iburst' >> /etc/ntp.conf
        sudo service ntp restart

    - name: Make sure ntp is started, and is enabled on restart.
      service: 
        name: ntp 
        state: started 
        enabled: yes


